name: Feature Report
description: File a Feature Report
title: "[Feature]: "
labels: ["feature"]

body:
  - type: textarea
    id: feature-contents
    attributes:
      label: Feature 설명
      description: 작업할 Feature에 대한 설명을 적어주세요.
      placeholder: ex. 사용자 위치 기반 기능
      value: |
        ## 기능 설명
        > 추가하려는 기능에 대해 간결하게 설명해주세요.   
        ##  작업 상세 내용 
        - [ ] todo
        - [ ] todo
    validations:
      required: true
